version: "3.8"

services:
  # 用來打包前端程式碼用的
  npm:
    image: node
    working_dir: /source
    volumes:
      - ..:/source
    tty: true
  # 主要資料庫
  mysql:
    image: mysql:5.7
    restart: always
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
        - "./data/db/mysql:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
  # 測試資料庫
  mysql_test:
    image: mysql:5.7
    restart: always
    ports:
      - "33062:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "${TEST_MYSQL_ROOT_PASSWORD}"
      MYSQL_USER: "${TEST_MYSQL_USER}"
      MYSQL_PASSWORD: "${TEST_MYSQL_PASSWORD}"
      MYSQL_DATABASE: "${TEST_MYSQL_DATABASE}"
